# Site settings
title: Segmentation Violation
email: kthelgason@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sigsegv.is" # the base hostname & protocol for your site
twitter_username: karitristan
github_username:  kthelgason

# Build settings
markdown: kramdown
